# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    hashi_stack: "puppet/hashi_stack"
    systemd: "puppet/systemd"
    file_capability: "stm/file_capability"
    archive: "puppet/archive"
    apt: "puppetlabs/apt"
    yum: "puppet/yum"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
      puppet_version: ">= 6.0.0"
  symlinks:
    vault: "#{source_dir}"
