name: PDK validate & test unit

on:
  pull_request:
  workflow_call:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate
        uses: athenahealth/action-pdk@v1
        with:
          action: validate

      - name: Run Unit Tests
        uses: athenahealth/action-pdk@v1
        with:
          action: test unit
